//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordle_SDD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordle_SDD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream audioHelpMenuVoiceOver {
            get {
                return ResourceManager.GetStream("audioHelpMenuVoiceOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgCrossIconDark {
            get {
                object obj = ResourceManager.GetObject("imgCrossIconDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgCrossIconLight {
            get {
                object obj = ResourceManager.GetObject("imgCrossIconLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgHelpIconDark {
            get {
                object obj = ResourceManager.GetObject("imgHelpIconDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgHelpIconLight {
            get {
                object obj = ResourceManager.GetObject("imgHelpIconLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSettingsIconDark {
            get {
                object obj = ResourceManager.GetObject("imgSettingsIconDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSettingsIconLight {
            get {
                object obj = ResourceManager.GetObject("imgSettingsIconLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSpeakerDark {
            get {
                object obj = ResourceManager.GetObject("imgSpeakerDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgSpeakerLight {
            get {
                object obj = ResourceManager.GetObject("imgSpeakerLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon wordleLogo {
            get {
                object obj = ResourceManager.GetObject("wordleLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AALII,AALST,AALTO,AARON,ABACA,ABACK,ABAFF,ABAFT,ABAMA,ABAMP,ABASE,ABASH,ABASK,ABATE,ABAVE,ABAYA,ABAZE,ABBAS,ABBEY,ABBIE,ABBOT,ABDAL,ABDAT,ABEAM,ABEAR,ABELE,ABHOR,ABIDE,ABIDI,ABIES,ABILA,ABILO,ABKAR,ABLER,ABLOW,ABMHO,ABNER,ABNET,ABODE,ABODY,ABOHM,ABOIL,ABOMA,ABOON,ABORD,ABORT,ABOUT,ABOVE,ABRAM,ABRET,ABRIM,ABRIN,ABRUS,ABSIT,ABUJA,ABUNA,ABURA,ABUSE,ABUTA,ABUZZ,ABWAB,ABYLA,ABYSM,ABYSS,ACANA,ACAPU,ACARA,ACARI,ACATE,ACCHO,ACCOY,ACCRA,ACEDY,ACERB,ACHAR,ACHEN,ACHER,ACHOR,ACIER,ACKEE,ACKER,ACKEY,ACLYS,ACMIC,ACNED,AC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordList {
            get {
                return ResourceManager.GetString("wordList", resourceCulture);
            }
        }
    }
}
